version: "3.9"

services:
  ufisadi:
    build: 
      context: .
    command: > 
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000

    container_name: ufisadi
    command: python manage.py runserver 0.0.0.0:8000
    
    environment:
      - SECRET_KEY=+16a2x$b1$h1wv2tw#lcy-%wwvf*7b$j%vy-(-$qoc@gp@l7r6
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=ufisadi_db
      - DB_USER=ufisadi_user
      - DB_PASS=ufisadi12345
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=ufisadi_db
      - POSTGRES_USER=ufisadi_user
      - POSTGRES_PASSWORD=ufisadi12345
