version: "3.9"

services:
  ufisadi:
    build: 
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000

    container_name: ufisadi
    command: python manage.py runserver 0.0.0.0:8000

    # environment:
    #   - DB_HOST=pgdb 
    #   - DB_NAME=ufisadi
    #   - DB_USER=ufisadi_user
    #   - DB_PASS=ufisadi
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   container_name: mysql

  #   environment:
  #     - MYSQL_DATABASE: 'ufisadi_db'
  #     - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  #   volumes:
  #     - ./data/mysql/db:/var/lib/mysql